### ISSUE TITLE
can you provide some basic example like download, play/pause, share etc. ??

### ISSUE THREAD

**Issue by MayurAmipara** [renaudcerrato/ToggleDrawable#1]

**Comment by renaudcerrato** [comment]
You can  look at the available implementations:

https://github.com/renaudcerrato/ToggleDrawable/blob/master/library/src/main/java/com/mypopsy/drawable/SearchArrowDrawable.java

https://github.com/renaudcerrato/ToggleDrawable/blob/master/library/src/main/java/com/mypopsy/drawable/SearchCrossDrawable.java

https://github.com/renaudcerrato/ToggleDrawable/blob/master/library/src/main/java/com/mypopsy/drawable/DrawerArrowDrawable.java

**Comment by MayurAmipara** [comment]
that is mention also in your document, i said for other general buttons
 !

**Comment by renaudcerrato** [comment]
That's an opensource library, feel free to send me a pull request =)
