### ISSUE TITLE
Replace appcompat dependency with support-annotations?

### ISSUE THREAD

**Issue by hidroh** [renaudcerrato/ToggleDrawable#2]
Hi, I notice that the core library does not really depend on `com.android.support:appcompat-v7:x.x.x` except for use of `?attr/colorAccent` in [`styles.xml`](https://github.com/renaudcerrato/ToggleDrawable/blob/master/library/src/main/res/values/styles.xml) and  annotations in Java.
- for use of `?attr/colorAccent`, maybe we can replace it with an `?android:attr/` attribute? It's a default value anyway.
- for annotations, replacing `com.android.support:appcompat-v7:x.x.x` with `com.android.support:support-annotations:x.x.x` would be sufficient.

Removing dependency with appcompat will greatly reduce method count and make the library more lightweight to be used.

**Comment by renaudcerrato** [comment]
done! Thanks!
