### ISSUE TITLE
How to animate automatically?

### ISSUE THREAD

**Issue by mehrdad-shokri** [renaudcerrato/ToggleDrawable#7]
Hi, I have a ``SearchCrossDrawable``
What I want to do is animate between the search icon and cross icon.  
Right now when I set ``setProgress(1)`` it just switches between search and cross without animation.  
Is there any way that I can animate automatically, Or I should Update progress in a loop manually?

**Comment by renaudcerrato** [comment]
You could use an [`ObjectAnimator`](https://developer.android.com/reference/android/animation/ObjectAnimator.html) to do that for example.

**Comment by mehrdad-shokri** [comment]
can you provide a code snippet?
